import Link from "next/link"
import Image from "next/image"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Terms of Service · Bloom",
  description: "The terms that govern your use of Bloom: what you can expect from us, and what we ask of you.",
}

const LAST_UPDATED = "June 5, 2026"

type Section = {
  title: string
  paragraphs?: string[]
  bullets?: string[]
}

const sections: Section[] = [
  {
    title: "1. Agreeing to these terms",
    paragraphs: [
      "Bloom (“Bloom”, “we”, “us”, or “our”) is a mental wellness platform offering mood tracking, private journaling, an AI companion called Aastha, and peer-to-peer conversations.",
      "By creating an account or using Bloom in any way, you agree to these Terms of Service. If you do not agree, please do not use Bloom.",
    ],
  },
  {
    title: "2. Who can use Bloom",
    paragraphs: [
      "You must be at least 18 years old, or the age of legal majority where you live, to use Bloom. By using Bloom you confirm that you meet this requirement and that the information you provide is accurate.",
    ],
  },
  {
    title: "3. Bloom is not medical care",
    paragraphs: [
      "Bloom is a wellness and self-reflection tool. It is not a medical or healthcare service, and it does not provide diagnosis, treatment, or professional advice.",
      "Aastha is an AI companion, not a licensed therapist, doctor, or counselor. People you meet through peer conversations are not professionals either. Nothing on Bloom should be treated as a substitute for care from a qualified professional. Always seek the advice of a professional for any questions about your health.",
    ],
  },
  {
    title: "4. Your account",
    paragraphs: [
      "You are responsible for keeping your login details secure and for everything that happens under your account. Let us know promptly if you believe your account has been accessed without your permission.",
    ],
  },
  {
    title: "5. Community conduct",
    paragraphs: [
      "Bloom’s peer conversations only work if everyone feels safe. When you connect with another person, you agree to be respectful and to keep the space supportive.",
    ],
    bullets: [
      "No harassment, hate, threats, or sexually explicit behavior.",
      "No recording, screenshotting, or sharing another person’s video, audio, or messages.",
      "No sharing of personal contact details or attempts to move conversations off Bloom.",
      "Use the report and skip tools if someone makes you uncomfortable.",
    ],
  },
  {
    title: "6. Your content",
    paragraphs: [
      "Your journals, messages, and mood entries belong to you. You grant Bloom only the limited permission needed to store and process your content so the service can function, for example sending your messages to our AI provider to generate Aastha’s replies.",
      "We do not sell your personal content. We may process it through trusted third-party services strictly to operate Bloom.",
    ],
  },
  {
    title: "7. AI responses",
    paragraphs: [
      "Aastha’s replies are generated by a third-party AI model and may be inaccurate, incomplete, or unsuitable for your situation. Use your own judgment, and never rely on Aastha for medical, legal, financial, or other professional decisions.",
    ],
  },
  {
    title: "8. Third-party services",
    paragraphs: [
      "Bloom relies on third-party services to function, including sign-in, AI, and video providers. Your use of those features may also be subject to the providers’ own terms. We are not responsible for third-party services we do not control.",
    ],
  },
  {
    title: "9. Our rights",
    paragraphs: [
      "Bloom reserves the right, at any time and at our sole discretion, to add, change, suspend, limit, or discontinue any part of the service. We may also remove content, restrict features, or suspend or terminate accounts, with or without notice, where we reasonably believe these Terms have been broken or to protect Bloom and its community.",
      "We may update these Terms from time to time. When we do, we’ll revise the date below, and your continued use of Bloom means you accept the updated Terms.",
    ],
  },
  {
    title: "10. Disclaimers & liability",
    paragraphs: [
      "Bloom is provided “as is” and “as available,” without warranties of any kind. To the fullest extent permitted by law, Bloom is not liable for any indirect, incidental, or consequential damages arising from your use of the service.",
    ],
  },
  {
    title: "11. Contact",
    paragraphs: [
      "Questions about these Terms? Reach us at adityasinghstuff@gmail.com.",
    ],
  },
]

export default function TermsPage() {
  return (
    <div
      className="min-h-screen relative overflow-hidden"
      style={{ background: "#f7f4ef", fontFamily: "var(--font-figtree), ui-sans-serif, sans-serif" }}
    >
      {/* Atmospheric blobs */}
      <div
        aria-hidden
        className="absolute pointer-events-none"
        style={{
          top: "-12%", right: "-8%",
          width: "480px", height: "480px",
          borderRadius: "50%",
          background: "rgba(198,113,86,0.10)",
          filter: "blur(90px)",
        }}
      />
      <div
        aria-hidden
        className="absolute pointer-events-none"
        style={{
          top: "40%", left: "-10%",
          width: "420px", height: "420px",
          borderRadius: "50%",
          background: "rgba(166,179,168,0.12)",
          filter: "blur(80px)",
        }}
      />

      {/* Header */}
      <header className="relative z-10 mx-auto max-w-3xl px-6 pt-10 md:px-8">
        <Link href="/" className="flex items-center gap-1 w-fit" style={{ marginLeft: "-4px" }}>
          <Image
            src="/logo.png"
            alt=""
            width={60}
            height={44}
            style={{ mixBlendMode: "multiply", marginRight: "-12px" }}
          />
          <span
            className="font-display"
            style={{ fontSize: "19px", letterSpacing: "-0.03em", color: "#28312C" }}
          >
            bloom
          </span>
        </Link>
      </header>

      {/* Body */}
      <main className="relative z-10 mx-auto max-w-3xl px-6 pb-24 pt-12 md:px-8">
        <div
          className="eyebrow flex items-center gap-2"
          style={{ color: "#A6B3A8", letterSpacing: "0.2em" }}
        >
          <span className="divider-dot" /> Legal
        </div>

        <h1
          className="font-display mt-4"
          style={{ fontSize: "44px", lineHeight: 1.04, letterSpacing: "-0.03em", color: "#28312C" }}
        >
          Terms of <span style={{ color: "#C67156", fontStyle: "italic" }}>Service</span>
        </h1>

        <p className="mt-4 text-sm" style={{ color: "rgba(93,104,98,0.7)" }}>
          Last updated {LAST_UPDATED}
        </p>

        <p className="mt-6 text-base leading-relaxed" style={{ color: "#5D6862" }}>
          A short, plain-language version of the rules for using Bloom. We&rsquo;ve tried to keep
          it gentle and honest, the same way we&rsquo;ve tried to build the app.
        </p>

        {/* Crisis callout */}
        <div
          className="mt-8 rounded-2xl p-6"
          style={{
            background: "rgba(198,113,86,0.07)",
            border: "1px solid rgba(198,113,86,0.22)",
          }}
        >
          <h2
            className="font-display"
            style={{ fontSize: "20px", letterSpacing: "-0.02em", color: "#28312C" }}
          >
            Bloom isn&rsquo;t a crisis service
          </h2>
          <p className="mt-2 text-sm leading-relaxed" style={{ color: "#5D6862" }}>
            If you&rsquo;re in danger or thinking about harming yourself, please don&rsquo;t wait for
            an app. Contact your local emergency number right away. In India, you can reach the
            KIRAN mental health helpline at <span style={{ color: "#28312C", fontWeight: 600 }}>1800-599-0019</span> (free, 24/7).
            Aastha and peer chats are here for the ordinary heavy days, not emergencies.
          </p>
        </div>

        {/* Sections */}
        <div className="mt-12 space-y-10">
          {sections.map((s) => (
            <section key={s.title}>
              <h2
                className="font-display"
                style={{ fontSize: "22px", letterSpacing: "-0.02em", color: "#28312C" }}
              >
                {s.title}
              </h2>
              {s.paragraphs?.map((p, i) => (
                <p key={i} className="mt-3 text-[15px] leading-relaxed" style={{ color: "#5D6862" }}>
                  {p}
                </p>
              ))}
              {s.bullets && (
                <ul className="mt-3 space-y-2">
                  {s.bullets.map((b, i) => (
                    <li key={i} className="flex gap-3 text-[15px] leading-relaxed" style={{ color: "#5D6862" }}>
                      <span
                        className="mt-2 w-1.5 h-1.5 rounded-full shrink-0"
                        style={{ background: "#C67156" }}
                      />
                      <span>{b}</span>
                    </li>
                  ))}
                </ul>
              )}
            </section>
          ))}
        </div>

        {/* Footer */}
        <div
          className="mt-16 pt-8 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"
          style={{ borderTop: "1px solid rgba(40,49,44,0.1)" }}
        >
          <p className="text-xs" style={{ color: "rgba(93,104,98,0.55)" }}>
            &copy; {new Date().getFullYear()} Bloom. Your wellbeing, our priority.
          </p>
          <Link
            href="/signup"
            className="text-sm font-semibold transition-colors hover:opacity-80"
            style={{ color: "#C67156" }}
          >
            Back to sign up &rarr;
          </Link>
        </div>
      </main>
    </div>
  )
}
